# Basic Config
seed: 2024
do_train: 1
task_id: 'test'
model: 'GPT4changePoints'

# Data Loader
delay: 1
size: 20

# Model Define
# Hidden Layer Config
d_model: 4096
prompt_length: 512
dropout: 0.5
llm_model: LLAMA
llm_layers: 30
freeze: True
pretrain: True
tmax: 20
cos: 1


# Optimization
num_workers: 10
itr: 1
train_epochs: 10
batch_size: 4
patience: 3
learning_rate: 0.0001
des: 'test'
loss: 'mse'
lradj: 'type1'
use_amp: False

# GPU
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0,1,2,3'

#changePoints
change_path: ./dataset/changePoints/^GSPC_OT_High_changePoints_div_num10_min_size2_jump3.csv

